# permissions for end users to view weathers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: weather-viewer-role
rules:
- apiGroups:
  - weather.alsup
  resources:
  - weathers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - weather.alsup
  resources:
  - weathers/status
  verbs:
  - get
