# permissions for end users to edit weathers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: weather-editor-role
rules:
- apiGroups:
  - weather.alsup
  resources:
  - weathers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - weather.alsup
  resources:
  - weathers/status
  verbs:
  - get
